# Generated by Django 4.1.7 on 2023-03-18 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='temperaturemeasurement',
            old_name='date_measurement',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='temperaturemeasurement',
            name='sensor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurement', to='measurement.sensor'),
        ),
    ]
