# Generated by Django 4.1.7 on 2023-03-18 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0003_alter_temperaturemeasurement_sensor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperaturemeasurement',
            name='sensor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurement', to='measurement.sensor'),
        ),
    ]
